Repository Append-IT/ant-design-blazor, pull requests merged in 2020-05, with the labels that each got.

#55 [FIX] Run Icon-sync monthly
  .github/workflows/icon-sync.yaml
Labels: maintenance

#59 [Git Actions] Change file extention sync-styles to .yaml
  .github/workflows/sync-styles.yaml
Labels: maintenance

#56 [FIX] Disabled works correct + tests
  docs/Append.AntDesign.Documentation/Components/Button/Actions.razor
  docs/Append.AntDesign.Documentation/Components/Button/Basic.razor
  docs/Append.AntDesign.Documentation/Components/Button/Ghost.razor
  docs/Append.AntDesign.Documentation/Components/Button/Icons.razor
  docs/Append.AntDesign.Documentation/Components/Button/Loading.razor
  source/Append.AntDesign/Components/Button/Button.razor
  tests/Append.AntDesign.Tests/Components/Button/ButtonSnapshots.razor
Labels: bug

#49 [WIP] Result
  docs/Append.AntDesign.Documentation/Components/Result/BadRequest.razor
  docs/Append.AntDesign.Documentation/Components/Result/Custom.razor
  docs/Append.AntDesign.Documentation/Components/Result/Error.razor
  docs/Append.AntDesign.Documentation/Components/Result/Index.md
  docs/Append.AntDesign.Documentation/Components/Result/Info.razor
  docs/Append.AntDesign.Documentation/Components/Result/NotFound.razor
  docs/Append.AntDesign.Documentation/Components/Result/Success.razor
  docs/Append.AntDesign.Documentation/Components/Result/Unauthorized.razor
  docs/Append.AntDesign.Documentation/Components/Result/Warning.razor
  docs/Append.AntDesign.Documentation/Shared/NavMenu.razor
  docs/Append.AntDesign.Documentation/wwwroot/css/documentation-styles.min.css
  source/Append.AntDesign/Components/Icon/IconTheme.cs
  source/Append.AntDesign/Components/Icon/IconType.cs
  source/Append.AntDesign/Components/Result/Result.less
  source/Append.AntDesign/Components/Result/Result.razor
  source/Append.AntDesign/Components/Result/Result.razor.cs
  source/Append.AntDesign/Components/Result/ResultStatus.cs
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.less
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.min.css
  source/Append.AntDesign/wwwroot/icons/internal/bad-request.svg
  source/Append.AntDesign/wwwroot/icons/internal/not-found.svg
  source/Append.AntDesign/wwwroot/icons/internal/unauthorized.svg
  tests/Append.AntDesign.Tests/Append.AntDesign.Tests.csproj
  tests/Append.AntDesign.Tests/Components/Result/ResultSnapshots.razor
Labels: enhancement

#54 Typography
  docs/Append.AntDesign.Documentation/Components/Typography/Basic.razor
  docs/Append.AntDesign.Documentation/Components/Typography/Index.md
  docs/Append.AntDesign.Documentation/Components/Typography/Interactive.razor
  docs/Append.AntDesign.Documentation/Components/Typography/TextComponent.razor
  docs/Append.AntDesign.Documentation/Components/Typography/TitleComponent.razor
  docs/Append.AntDesign.Documentation/Pages/Experiment.razor
  docs/Append.AntDesign.Documentation/Shared/NavMenu.razor
  source/Append.AntDesign/Components/Tooltip/Tooltip.razor
  source/Append.AntDesign/Components/Typography/Paragraph.razor
  source/Append.AntDesign/Components/Typography/Paragraph.razor.cs
  source/Append.AntDesign/Components/Typography/Text.razor
  source/Append.AntDesign/Components/Typography/Text.razor.cs
  source/Append.AntDesign/Components/Typography/Title.razor
  source/Append.AntDesign/Components/Typography/Title.razor.cs
  source/Append.AntDesign/Components/Typography/Typography.less
  source/Append.AntDesign/Components/Typography/TypographyBase.cs
  source/Append.AntDesign/Components/Typography/TypographyTitleLevel.cs
  source/Append.AntDesign/Components/Typography/TypographyType.cs
  source/Append.AntDesign/Core/Extensions.cs
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.less
  tests/Append.AntDesign.Tests/Components/Typography/TypographySnapshots.razor
Labels: enhancement

#68 [InputNumber] Base + docs + tests
  docs/Append.AntDesign.Documentation/Components/InputNumber/Basic.razor
  docs/Append.AntDesign.Documentation/Components/InputNumber/Decimals.razor
  docs/Append.AntDesign.Documentation/Components/InputNumber/Disabled.razor
  docs/Append.AntDesign.Documentation/Components/InputNumber/Formatter.razor
  docs/Append.AntDesign.Documentation/Components/InputNumber/Index.md
  docs/Append.AntDesign.Documentation/Components/InputNumber/Sizes.razor
  docs/Append.AntDesign.Documentation/Shared/NavMenu.razor
  docs/Append.AntDesign.Documentation/wwwroot/css/documentation-styles.min.css
  source/Append.AntDesign/Components/InputNumber/InputNumber.less
  source/Append.AntDesign/Components/InputNumber/InputNumber.razor
  source/Append.AntDesign/Components/InputNumber/InputNumber.razor.cs
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.less
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.min.css
  tests/Append.AntDesign.Tests/Components/InputNumber/InputNumberSnapshots.razor
Labels: enhancement

#74 [InputNumber] bugfix tests
  docs/Append.AntDesign.Documentation/Components/InputNumber/Formatter.razor
  source/Append.AntDesign/Components/InputNumber/InputNumber.razor.cs
  tests/Append.AntDesign.Tests/Components/InputNumber/InputNumberSnapshots.razor
Labels: bug

#75 [InputNumber] Make code culture independent
  source/Append.AntDesign/Components/InputNumber/InputNumber.razor
  source/Append.AntDesign/Components/InputNumber/InputNumber.razor.cs
  tests/Append.AntDesign.Tests/Components/InputNumber/InputNumberSnapshots.razor
Labels: bug, enhancement

#82 Suppress warning 0649 for avatarRef & textRef
  source/Append.AntDesign/Components/Avatar/Avatar.razor.cs
Labels: maintenance

#83 Create testOnPR workflow file
  .github/workflows/test-on-pr.yaml
  docs/Append.AntDesign.Documentation/wwwroot/css/documentation-styles.min.css
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.min.css
Labels: enhancement

#80 [Notification] implementation
  docs/Append.AntDesign.Documentation/Components/Notification/Basic.razor
  docs/Append.AntDesign.Documentation/Components/Notification/CustomCloseButton.razor
  docs/Append.AntDesign.Documentation/Components/Notification/CustomIcon.razor
  docs/Append.AntDesign.Documentation/Components/Notification/CustomStyle.razor
  docs/Append.AntDesign.Documentation/Components/Notification/Destroy.razor
  docs/Append.AntDesign.Documentation/Components/Notification/Duration.razor
  docs/Append.AntDesign.Documentation/Components/Notification/Index.md
  docs/Append.AntDesign.Documentation/Components/Notification/Placement.razor
  docs/Append.AntDesign.Documentation/Components/Notification/UpdateContent.razor
  docs/Append.AntDesign.Documentation/Components/Notification/WithIcon.razor
  docs/Append.AntDesign.Documentation/Shared/MainLayout.razor
  docs/Append.AntDesign.Documentation/Shared/NavMenu.razor
  docs/Append.AntDesign.Documentation/wwwroot/css/documentation-styles.min.css
  source/Append.AntDesign/Append.AntDesign.csproj
  source/Append.AntDesign/Components/Notification/Notification.less
  source/Append.AntDesign/Components/Notification/Notification.razor
  source/Append.AntDesign/Components/Notification/Notification.razor.cs
  source/Append.AntDesign/Components/Notification/NotificationContainer.razor
  source/Append.AntDesign/Components/Notification/NotificationContainer.razor.cs
  source/Append.AntDesign/Components/Notification/NotificationList.cs
  source/Append.AntDesign/Components/Notification/NotificationListItem.cs
  source/Append.AntDesign/Components/Notification/NotificationPlacement.cs
  source/Append.AntDesign/Components/Notification/NotificationType.cs
  source/Append.AntDesign/Components/Notification/config/NotificationConfigOptions.cs
  source/Append.AntDesign/Components/Notification/config/NotificationGlobalConfigOptions.cs
  source/Append.AntDesign/Core/ServiceCollectionExtensions.cs
  source/Append.AntDesign/Services/Notifications/NotificationService.cs
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.less
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.min.css
Labels: enhancement

#79 [Steps] implementation
  docs/Append.AntDesign.Documentation/Components/Steps/Basic.razor
  docs/Append.AntDesign.Documentation/Components/Steps/Clickable.razor
  docs/Append.AntDesign.Documentation/Components/Steps/CustomizedProgressDot.razor
  docs/Append.AntDesign.Documentation/Components/Steps/DotStyle.razor
  docs/Append.AntDesign.Documentation/Components/Steps/Error.razor
  docs/Append.AntDesign.Documentation/Components/Steps/Icon.razor
  docs/Append.AntDesign.Documentation/Components/Steps/Index.md
  docs/Append.AntDesign.Documentation/Components/Steps/Nav.razor
  docs/Append.AntDesign.Documentation/Components/Steps/SmallSize.razor
  docs/Append.AntDesign.Documentation/Components/Steps/StepNext.razor
  docs/Append.AntDesign.Documentation/Components/Steps/Vertical.razor
  docs/Append.AntDesign.Documentation/Components/Steps/VerticalSmall.razor
  docs/Append.AntDesign.Documentation/Shared/NavMenu.razor
  docs/Append.AntDesign.Documentation/wwwroot/css/documentation-styles.min.css
  source/Append.AntDesign/Components/Steps/Step.razor
  source/Append.AntDesign/Components/Steps/Step.razor.cs
  source/Append.AntDesign/Components/Steps/Steps.less
  source/Append.AntDesign/Components/Steps/Steps.razor
  source/Append.AntDesign/Components/Steps/Steps.razor.cs
  source/Append.AntDesign/Components/Steps/StepsDirection.cs
  source/Append.AntDesign/Components/Steps/StepsSize.cs
  source/Append.AntDesign/Components/Steps/StepsStatus.cs
  source/Append.AntDesign/Components/Steps/StepsType.cs
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.less
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.min.css
  tests/Append.AntDesign.Tests/Components/Steps/StepsSnapshots.razor
Labels: enhancement

#87 [Maintenance] Update bUnit to Beta-7
  docs/Append.AntDesign.Documentation/wwwroot/css/documentation-styles.min.css
  tests/Append.AntDesign.Tests/Append.AntDesign.Tests.csproj
  tests/Append.AntDesign.Tests/Components/Alert/AlertSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Avatar/AvatarSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Badge/BadgeSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Button/ButtonSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Input/InputSnapshots.razor
  tests/Append.AntDesign.Tests/Components/InputNumber/InputNumberSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Result/ResultSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Steps/StepsSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Switch/SwitchSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Tag/TagSnapshots.razor
  tests/Append.AntDesign.Tests/Components/Typography/TypographySnapshots.razor
Labels: maintenance

#72 [WIP] Spin
  docs/Append.AntDesign.Documentation/Components/Spin/Basic.razor
  docs/Append.AntDesign.Documentation/Components/Spin/Container.razor
  docs/Append.AntDesign.Documentation/Components/Spin/Delay.razor
  docs/Append.AntDesign.Documentation/Components/Spin/Description.razor
  docs/Append.AntDesign.Documentation/Components/Spin/Embedded.razor
  docs/Append.AntDesign.Documentation/Components/Spin/Index.md
  docs/Append.AntDesign.Documentation/Components/Spin/Indicator.razor
  docs/Append.AntDesign.Documentation/Components/Spin/Size.razor
  docs/Append.AntDesign.Documentation/Components/Spin/Wrapper.razor
  docs/Append.AntDesign.Documentation/Shared/NavMenu.razor
  docs/Append.AntDesign.Documentation/wwwroot/css/documentation-styles.min.css
  source/Append.AntDesign/Components/Spin/Spin.less
  source/Append.AntDesign/Components/Spin/Spin.razor
  source/Append.AntDesign/Components/Spin/Spin.razor.cs
  source/Append.AntDesign/Components/Spin/SpinSize.cs
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.less
  source/Append.AntDesign/wwwroot/css/ant-design-blazor.min.css
  tests/Append.AntDesign.Tests/Components/Spin/SpinSnapshots.razor
Labels: enhancement
